# Tarea 2

Elaborado por: Anthony Cascante, Michael Yip

## Tutorial de Pandas

Este tutorial muestra las funciones basicas de para el uso de la biblioteca Pandas orientado al preprocesamiento de datos.
Aunque no se muestren la totalidad de funciones que ofrece la biblioteca Pandas, se muestra y ejemplifica las funciones que se consideren de importancia

### Dependencias

Se importan las bibliotecas necesarias para la implementacion del tutorial

In [1]:
import pandas as pd

### Carga de Dataset

Se utiliza el set de datos *daily-min-temperatures.csv*

La funcion **read_csv** toma como input una ruta donde se encuentran el set datos en formato CSV y los carga a la variable *daily_min_temperatures*

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [5]:
df.loc[0:3]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0

In [9]:
df.iloc[:, 2:7]

     BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction
0               72             35        0  33.6                     0.627
1               66             29        0  26.6                     0.351
2               64              0        0  23.3                     0.672
3               66             23       94  28.1                     0.167
4               40             35      168  43.1                     2.288
5               74              0        0  25.6                     0.201
6               50             32       88  31.0                     0.248
7                0              0        0  35.3                     0.134
8               70             45      543  30.5                     0.158
9               96              0        0   0.0                     0.232
10              92              0        0  37.6                     0.191
11              74              0        0  38.0                     0.537
12              80              0        0  27.1                     1.441
13              60             23      846  30.1                     0.398
14              72             19      175  25.8                     0.587
15               0              0        0  30.0                     0.484
16              84             47      230  45.8                     0.551
17              74              0        0  29.6                     0.254
18              30             38       83  43.3                     0.183
19              70             30       96  34.6                     0.529
20              88             41      235  39.3                     0.704
21              84              0        0  35.4                     0.388
22              90              0        0  39.8                     0.451
23              80             35        0  29.0                     0.263
24              94             33      146  36.6                     0.254
25              70             26      115  31.1                     0.205
26              76              0        0  39.4                     0.257
27              66             15      140  23.2                     0.487
28              82             19      110  22.2                     0.245
29              92              0        0  34.1                     0.337
..             ...            ...      ...   ...                       ...
738             60             17      160  36.6                     0.453
739             74              0        0  39.5                     0.293
740             80             37      150  42.3                     0.785
741             44             20       94  30.8                     0.400
742             58             18      116  28.5                     0.219
743             94              0        0  32.7                     0.734
744             88             37      140  40.6                     1.174
745             84             33      105  30.0                     0.488
746             94             41        0  49.3                     0.358
747             74             41       57  46.3                     1.096
748             70             22      200  36.4                     0.408
749             62              0        0  24.3                     0.178
750             70              0        0  31.2                     1.182
751             78             39       74  39.0                     0.261
752             62             24        0  26.0                     0.223
753             88             44      510  43.3                     0.222
754             78             32        0  32.4                     0.443
755             88             39      110  36.5                     1.057
756             90             41        0  32.0                     0.391
757             72              0        0  36.3                     0.258
758             76              0        0  37.5                     0.197
759             92              0        0  35.5                     0.278
760             58             26       16  28.4                     0.766
761             74             31        0  44.0                     0.403
762             62              0        0  22.5                     0.142
763             76             48      180  32.9                     0.171
764             70             27        0  36.8                     0.340
765             72             23      112  26.2                     0.245
766             60              0        0  30.1                     0.349
767             70             31        0  30.4                     0.315

[768 rows x 5 columns]

In [7]:
df.iloc[4:7, :]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1

In [8]:
df.loc[:7]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0